#!/usr/bin/env zsh
##? envsubst - fallback wrapper in the event envsubst command does not exist

# function envsubst {
if (( $+commands[envsubst] )); then 
  command envsubst "$@"
else
  python -c 'import os,sys;[sys.stdout.write(os.path.expandvars(l)) for l in sys.stdin]'
fi
# }
